### ISSUE TITLE
Nix-MiniBrowser: page layout is broken after window resize in touch mode

### ISSUE THREAD

**Issue by ebalint** [WebKitNix/webkitnix#33] opened 2013-10-22 08:18 UTC
In touch mode, if you resize the window, in most of the cases the webpage's size doesn't adapt to the new window size.

**Comment by hugopl** [comment] 2013-10-22 14:37
Do you have some example or steps to reproduce this? I tried here and couldn't reproduce this.

**Comment by ebalint** [comment] 2013-10-22 16:02
Steps to reproduce: you open google.com in the MiniBrowser in touch mode. Then you resize the window to full size, and after that you resize it to previous size. The page will be smaller than the window, and there will be a blank space on the left side.

i'm working on this bug, and i've found a fix.

what do you think, is it okay?

patch:

https://gist.github.com/ebalint/4e6ecf189cb658bf3647

**Comment by ebalint** [comment] 2013-10-22 16:03
Beside this, i've found another problem with the window resizing / zooming. If you're on a page, and go to another page, then resize the window and go back to previous page, the zooming on the previous page will be incorrect. For this bug I haven't found a solution yet, but i'm working on it.

**Comment by hugopl** [comment] 2013-10-22 16:46
Your fix seems right.

I wasn't able to reproduce because the bug happens only when the maxinimize button is clicked, if the window is resized using the window border handlers the bug doesn't occur.

**Comment by qrwteyrutiyoup** [comment] 2013-10-28 15:59
Fixed by ca0a13c7.

**Closed as completed by qrwteyrutiyoup** 2013-10-28 15:59 UTC
